### ISSUE TITLE
JDBC PostgreSQL

### ISSUE THREAD

**Issue by shizacat** [DataTurks/DataTurks#27]
Can you tell, as to add JDBC driver for Postgresql.
https://jdbc.postgresql.org/download.html
I want use external db server.
it is my config:
```
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: org.postgresql.Driver
    # the username
    user: dataturks
    # the password
    password: dataturks
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:postgresql://psql.server.local:5432/dataturks
```
